#!/usr/bin/env python3
"""build_drivecode.py - assemble the 1541 drive gate and emit it as C data.

Keeps one source of truth: src/drivecode_1541.s is assembled with ca65/ld65
to a flat binary at $0600, and this script turns that binary into
src/drivecode_1541.h so the C side never carries hand typed opcodes.

usage: tools/build_drivecode.py
(C) 2026 Robert Mech. Licence GPL-3.0-or-later.
"""
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "src" / "drivecode_1541.s"
CFG = ROOT / "tools" / "drivecode.cfg"
BUILD = ROOT / "build"
OUT = ROOT / "src" / "drivecode_1541.h"

LOAD_ADDR = 0x0600


def run(cmd):
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        sys.exit(f"{cmd[0]} failed:\n{r.stdout}{r.stderr}")


def main():
    BUILD.mkdir(exist_ok=True)
    obj = BUILD / "drivecode_1541.o"
    binf = BUILD / "drivecode_1541.bin"
    run(["ca65", "-o", str(obj), str(SRC)])
    run(["ld65", "-C", str(CFG), "-o", str(binf), str(obj)])

    data = binf.read_bytes()

    # The host patches the last byte (ENDTRK), so pin its offset here rather
    # than letting the C side guess.
    endtrk_off = len(data) - 1

    lines = [
        "/* drivecode_1541.h - GENERATED by tools/build_drivecode.py.",
        " * Do not edit: change src/drivecode_1541.s and run the script.",
        " * (C) 2026 Robert Mech. Licence GPL-3.0-or-later.",
        " */",
        "",
        "#ifndef DRIVECODE_1541_H",
        "#define DRIVECODE_1541_H",
        "",
        f"#define DC1541_ADDR   0x{LOAD_ADDR:04x}u",
        f"#define DC1541_SIZE   {len(data)}u",
        f"#define DC1541_ENDTRK 0x{LOAD_ADDR + endtrk_off:04x}u",
        "",
        "static const unsigned char dc1541[DC1541_SIZE] = {",
    ]
    for i in range(0, len(data), 8):
        chunk = ", ".join(f"0x{b:02x}" % () if False else f"0x{b:02x}"
                          for b in data[i:i + 8])
        lines.append(f"    {chunk},")
    lines += ["};", "", "#endif /* DRIVECODE_1541_H */", ""]
    OUT.write_text("\n".join(lines))
    print(f"{len(data)} bytes at ${LOAD_ADDR:04x}, ENDTRK at "
          f"${LOAD_ADDR + endtrk_off:04x} -> {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
