/* drivecode_1541.h - GENERATED by tools/build_drivecode.py.
 * Do not edit: change src/drivecode_1541.s and run the script.
 * (C) 2026 Robert Mech. Licence MIT.
 */

#ifndef DRIVECODE_1541_H
#define DRIVECODE_1541_H

#define DC1541_ADDR   0x0600u
#define DC1541_SIZE   26u
#define DC1541_ENDTRK 0x0619u

static const unsigned char dc1541[DC1541_SIZE] = {
    0xa5, 0x51, 0x30, 0x12, 0xcd, 0x19, 0x06, 0x90,
    0x0d, 0xa9, 0xff, 0x85, 0x51, 0xa9, 0x00, 0x85,
    0x50, 0xa9, 0x01, 0x4c, 0x69, 0xf9, 0x4c, 0xc7,
    0xfa, 0x00,
};

#endif /* DRIVECODE_1541_H */
